name = "ManianowniaPack"
author = "Manianownia"
version = "1.17.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0414e3d9237d236c57598cede40d0fe96fe6214dfbf782df6010c2ad985f64ea"

[versions]
fabric = "0.19.5"
minecraft = "1.20.1"
