name = "ManianowniaPack"
author = "Manianownia"
version = "1.12.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea25d14feef4379cedb5406a949d470151ff6b20ab231200ad52b5801656a286"

[versions]
fabric = "0.19.5"
minecraft = "1.20.1"
