# ManianowniaPack: z Essential Commands włączony jest tylko /spawn (ustawianie: /spawn set, OP)
enable_back=false
enable_home=false
enable_spawn=true
enable_tpa=false
enable_warp=false
enable_nick=false
enable_rtp=false
enable_fly=false
enable_invuln=false
enable_workbench=false
enable_anvil=false
enable_enderchest=false
enable_wastebin=false
enable_experimental_essentialsx_converter=false
enable_top=false
enable_gametime=false
enable_motd=false
enable_afk=false
enable_day=false
enable_rules=false
enable_bed=false
enable_feed=false
enable_heal=false
enable_extinguish=false
enable_suicide=false
enable_night=false
enable_repair=false
enable_near=false
enable_delete_all_player_data=false
teleport_delay=3.0
teleport_cooldown=10.0
teleport_interrupt_on_damaged=true
teleport_interrupt_on_move=true
teleport_interrupt_on_move_max_blocks=1.5
allow_teleport_between_dimensions=true
nicknames_in_player_list=false
use_permissions_api=false
