# ManianowniaPack - zalecane ustawienia serwera (skopiuj wartości do swojego server.properties)
motd=§6§lManianowniaPack §7| §bserwer Manianowni
difficulty=hard
gamemode=survival
pvp=true
# loty: maszyny Create, Stół lewitacji z BOMD, smok z AdventureZ - bez tego serwer wyrzuca graczy za "latanie"
allow-flight=true
spawn-protection=0
view-distance=8
simulation-distance=6
entity-broadcast-range-percentage=75
# brak automatycznego wyłączania serwera przy dłuższym przycięciu (generowanie terenu, bossowie)
max-tick-time=-1
sync-chunk-writes=false
network-compression-threshold=256
white-list=true
enforce-whitelist=true
online-mode=true
max-players=12
enable-command-block=false
level-name=world
